  version: '3.8'
  
  services:
    mlflow:
      build: 
        context: .
        dockerfile: docker/mlflow/Dockerfile
      ports:
        - "5001:5000" 
      volumes:
        - mlflow-artifacts:/mlflow/artifacts
        - mlflow-data:/mlflow/mlruns
      networks:
        - ml-network
      environment:
        - MLFLOW_TRACKING_URI=http://localhost:5001
        - MLFLOW_ARTIFACT_ROOT=/mlflow/artifacts
        - MLFLOW_BACKEND_STORE_URI=sqlite:////mlflow/mlruns/mlflow.db
  # Explicitly define volume
    

    airflow-webserver:
      build:
        context: .
        dockerfile: docker/airflow/Dockerfile
      ports:
        - "8080:8080"
      volumes:
        - ./airflow/dags:/opt/airflow/dags
        - ./src:/opt/airflow/src
        - ./logs:/opt/airflow/logs
        - ./config:/opt/airflow/config
      environment:
        - AIRFLOW__CORE__LOAD_EXAMPLES=False
        - AIRFLOW__CORE__EXECUTOR=LocalExecutor
        - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:airflow@postgres/airflow
        - MLFLOW_TRACKING_URI=http://mlflow:5001
        - AIRFLOW_HOME=/opt/airflow
      depends_on:
        - postgres
        - airflow-init
        - mlflow
      
      networks:
        - ml-network

    airflow-scheduler:
      build:
        context: .
        dockerfile: docker/airflow/Dockerfile
      volumes:
        - ./airflow/dags:/opt/airflow/dags
        - ./src:/opt/airflow/src
        - ./logs:/opt/airflow/logs
      environment:
        - AIRFLOW__CORE__LOAD_EXAMPLES=False
        - AIRFLOW__CORE__EXECUTOR=LocalExecutor
        - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:airflow@postgres/airflow
        - MLFLOW_TRACKING_URI=http://mlflow:5001
        - AIRFLOW_HOME=/opt/airflow
      command: airflow scheduler
      depends_on:
        - postgres
        - airflow-init
        - mlflow
      
      networks:
        - ml-network

    postgres:
      image: postgres:13
      environment:
        - POSTGRES_USER=airflow
        - POSTGRES_PASSWORD=airflow
        - POSTGRES_DB=airflow
      volumes:
        - postgres-data:/var/lib/postgresql/data
      networks:
        - ml-network

    airflow-init:
      build:
        context: .
        dockerfile: docker/airflow/Dockerfile
      environment:
        - AIRFLOW__CORE__LOAD_EXAMPLES=False
        - AIRFLOW__CORE__EXECUTOR=LocalExecutor
        - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:airflow@postgres/airflow
        - AIRFLOW_HOME=/opt/airflow
      command: airflow db init
      depends_on:
        - postgres
      networks:
        - ml-network

    api:
      build:
        context: .
        dockerfile: docker/api/Dockerfile
      ports:
        - "8000:8000"
      volumes:
        - ./models:/app/models
      environment:
        - MLFLOW_TRACKING_URI=http://mlflow:5001
      depends_on:
        - mlflow
      networks:
        - ml-network

  networks:
    ml-network:
      driver: bridge

  volumes:
    mlflow-artifacts:
     driver: local
    mlflow-data:
      driver: local
    postgres-data: